# Generated by Django 4.2.30

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def populate_product_skus(apps, schema_editor):
    Product = apps.get_model("products", "Product")

    for product in Product.objects.filter(sku__isnull=True).iterator():
        product.sku = f"PRD-{product.pk:06d}"
        product.save(update_fields=["sku"])


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_expand_category"),
        ("suppliers", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelTable(
            name="product",
            table="products",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="price",
            new_name="selling_price",
        ),
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="barcode",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.URLField(blank=True, default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="suppliers.supplier",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="cost_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00"))
                ],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="minimum_stock",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.CharField(default="piece", max_length=50),
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("discontinued", "Discontinued"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="categories.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="selling_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00"))
                ],
            ),
        ),
        migrations.RunPython(
            populate_product_skus,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
